---
- hosts: localhost
  tasks:
    - name: Change creation using the SNOW RECORD modules
      snow_record:
        username: dinesh12
        password: "Comnet@9212"
        instance: dev23907
        state: present
        table: change_request
        data:
            description: |
               Extend the filesystem fir the server {{ CI_NAME }}
               requetsed disk additin {{ disk_size }}
               requested task number {{TS_NO }}
               from 4gb to 8Gb
            short_description: " Extend the filesystem fir the server {{ CI_NAME}} from 4gb to 8Gb "
            ci_class: "cmdb_ci"
            cmdb_ci: "{{ CI_NAME }}"
            start_date: '{{ ansible_date_time.date }} {{ansible_date_time.time }}'    ## convert utc to CST time  ##
            u_backout_time: '1970-01-01 01:00:00'
            u_implementation_time: '1970-01-01 01:00:00 '
            assignment_group: "Server Ops Linux "
            assigned_to: "Dinesh shankar"
            u_implementation_plan: |
                login the recpective vcnter
                add the disk from the datastore
            u_implementation_test_plan: |
                  vaidate .
            u_implementation_test_results: NA
            backout_plan: "Restore the server from backup"
            type: 'normal'
            risk: '3'
            state: '-4'
            priority: '4'
      register: output

    - name: Create a simple Connector Card for mail approval
      office_365_connector_card:
        #webhook: https://levi.webhook.office.com/webhookb2/f2c731af-0a05-4bbf-a6e0-d3709cbb0ead@45cb9485-673d-45df-a2f0-27486343afda/IncomingWebhook/3b01d1a714134f7dab3dfe3eeca47442/51d2d3cf-536c-4ab3-8d9d-815d33a497b7
        webhook: https://levi.webhook.office.com/webhookb2/5ffab7ed-833d-4597-b533-0681745f4f27@45cb9485-673d-45df-a2f0-27486343afda/IncomingWebhook/769caf3d9c484d3593c1c699a8a0b138/215641d8-345d-41fd-8684-0833c7c1e06d
        summary: This is the summary property
        title: "Request for  Change  approval for the Change : {{ output.record[0]['number'] }}"
        text: "{{ ansible_date_time.date }} {{ ansible_date_time.time }} {{ ansible_date_time.tz }}"
        color: E81123

        sections:
        - title: Change Details
          activity_image: https://th.bing.com/th/id/OIP.n_Wwz6e0e1QKy14WP_73rgHaD8?pid=ImgDet&rs=1
          activity_title: "{{ output.record[0]['number']}} :  {{ output.record[0]['short_description']}}"
#          activity_title: "{{ chg }}"
          activity_text: "Approve it from snow : https://dev23907.service-now.com/now/nav/ui/classic/params/target/sysapproval_approver.do%3Fsys_id%3D442f40252fc6511025d5a1fef699b613%26sysparm_record_target%3Dsysapproval_approver%26sysparm_record_row%3D2%26sysparm_record_rows%3D4%26sysparm_record_list%3Dsysapproval%253Dc71f00252fc6511025d5a1fef699b6c1%255EORDERBYorder"
#        - title: Change Outcome
#          facts:
#          - name: Patching Status
#            value: "{{code}}"
      #delegate_to: localhost
